config/routes.rb
InquirlyNew::Application.routes.draw do

  ActiveAdmin.routes(self)
  match '/about' => "static#about", via: :get
  match '/help' => "static#help", via: :get
  post "/transaction" => "payments#handler"
  post "/response_handler" => "payments#response_handler"
  resources :tenants do
    collection do
      post 'change_tenant_status'
      get 'check_caller_id'
      get 'check_verify_caller_ids'
    end
  end
  resources :corporate_users do
    collection do
     get 'mapping_roles'
     post 'update_user_roles'
     post 'reset_password'
     get 'mapping_tenant'
     put 'update_tenant_users'
     get 'search_tenant_name'
     get 'search_user'
     get 'search_user_by_email'
     post 'change_user_status'
     get 'get_all_user'
    end
  end

  match '/', to: 'home#enterprise_login', constraints: { subdomain: /.+/ }, via: [:get, :post, :put, :patch, :delete]
devise_scope :user do
    authenticated :user do
      root 'dashboard#index', as: :authenticated_root
    end

    unauthenticated :user do
      root  'home#index'
    end
  end
  devise_for :users, :controllers => {sessions: "users/sessions", registrations: "users/registrations", passwords: "users/passwords", omniauth_callbacks: "users/omniauth_callbacks", confirmations: "users/confirmations", unlocks: "users/unlocks"}, :path_names => {sign_in: "login", sign_up: "register"}

  # devise_scope :user do
  #   match "/users/auth/facebook/callback", :to => "users/omniauth_callbacks#facebook", via: :get
  #   match '/users/auth/twitter/callback' => "users/omniauth_callbacks#twitter", via: :get
  #   match '/users/auth/google_oauth2/callback' => "users/omniauth_callbacks#google", via: :get
  #   match '/users/auth/linkedin/callback' => "users/omniauth_callbacks#linkedin", via: :get
  # end

  devise_scope :user do
    match "/users/auth/facebook/callback", :to => "users/omniauth_callbacks#facebook", via: :get
    match '/users/auth/twitter/callback' => "users/omniauth_callbacks#twitter", via: :get
    match '/users/auth/google_oauth2/callback' => "users/omniauth_callbacks#google", via: :get
    match '/users/auth/linkedin/callback' => "users/omniauth_callbacks#linkedin", via: :get
    match 'auth/:provider/failure', :to => "users/omniauth_callbacks#failure", via: :get
    match '/users/confirmation', :to => "users/confirmations#create", :via => :post
    match '/users/confirmation/new', :to => "users/confirmations#new", :via => :get
    match '/users/confirmation', :to => "users/confirmations#show", :via => :get
    match '/users/validate_user', :to => "users/sessions#validate_user_data", :via => :post
  end

  # Import
  resources :imports do
    collection do
    post 'create_customer_info'
    get 'csv_template'
    get 'customer_data'
    end
  end

  resources :payments do
    collection do
    get 'merchant_test'
    post 'post_to_zaakpay'
    post 'z_response'
    post 'send_cancel_email'
    get 'download_success'
    post 'update_billing'
    post 'update_payment_details'
    get 'get_user_plan_details'
    get 'get_user_emails'
    end
  end

#  match "/import_data", :to => "imports#import_data", via: :post
  match "/user_info_list" => "question#user_info_list", via: :get
  # Account
  resources :account do
    collection do
      #get 'upgrade'
      #get 'downgrade'
      get 'change_plan'
      post 'social_login'
      get 'company_settings'
      #put 'update_company_info'
      get 'transaction_history'
      post 'valid_email'
      get 'user_account'
      get 'get_customer_info'
      post 'add_social_account'
      post 'account_attachment'
      get 'profile_header'
    end
  end

#api calls
 get '/transaction_history' => 'account#transaction_history'
 post '/valid_email' => 'account#valid_email'
 get '/get_inquirly_user' => 'home#get_inquirly_user'

  resources :question do
    match '/answer' => "question#answer", via: :get
    member { post 'upload_logo'}
    member { post 'customize'}
    member { post 'generate_bity_url'}
    member { get 'get_style'}
    member { get 'get_image'}
    member { get 'get_detail'}
    member { get 'view_response_by_provider'}
    member { get 'view_response_by_location'}
    member { post 'update_question_status'}
    member { get 'default_settings'}
    get :deactivate
    get :preview
    get :search, :on => :collection
    get :share_question, :on => :collection

    collection do
      get 'index'
      get 'single_question'
      get 'multiple_question'
      get 'yes_no_question'
      get 'comment_question'
      get 'qrcode_active_inactive'
      #get 'default_settings'
      post 'question_status_change'
      post 'question_video_upload', :as => "video_upload"
      get 'sentiment_analyze'
      post 'show_question_wordcloud'
     end
  end

# in web its in get request but in api post
post '/qst_deactivate', :to => 'question#deactivate'
get '/home/signup' => 'home#signup_form'
get '/home/signin' => 'home#signin_form'
get '/home/forgot_password' => 'home#forgot_password_form'
post '/share/filter_converted_leads/:remainder', :to => "share#filter_converted_leads"

  resources :share do
   collection { get 'show' }
   member do
     get 'share_to_social_nw'
     get 'show_sms'
     post 'share_sms'
     get 'show_qr'
     get 'show_embed_code'
     post 'share_email'
     post 'activate_qr'
     get 'show_call_list'
     post 'share_call'
     post 'make_demo_call'
     get 'show_email'
   end
   collection do
   post 'make_call'
   post 'api_qrcode_url'
   get 'social_status_change'
   post 'call_handle'
   get 'handle_gather'
   get 'qrcode_url'
   get 'customers_data_grid'
   get 'qrdownload'
   get 'listeners_page'
   post 'check_customer_limit'
   post 'mandril_report'
   post 'twillo_call_report'
   post 'share_facebook'
   get 'customer_data_collection'
    end
  end


  resources :surveys do
   collection do
     get 'show'
     get 'states'
     post 'show_question'
     get 'update_embed_status'
   end
   member do
     post 'response_save'
     post 'response_email_verify'
     post 'create_user_info'
     get 'embed_survey'
     post 'show_embed_survey'
     post 'save_embed_response'
   end
  end

 resources :downloads do
   collection do
     #get 'download_pdf'
     get 'download_csv'
   end
 end

 resources :customers do
    collection do
    get 'get_customer_email'
    # get 'index'
    # post 'create'
    # put 'update'
    # delete 'destroy'
    get 'email_duplication_check'
    get 'mobile_duplication_check'
    post 'delete_selected'
    post 'remove_social_account'
    end
 end

 resources :answers do
  collection do
    #get 'sentiment_analyze'
    get 'report'
  end
 end


  get 'fill_sugg_qst' => 'question#fill_sugg_qst'

  resources :dashboard, :only => [:index] do
    collection do
      get 'social_media_analytics'
      get 'get_customers_by_location'
      get 'total_gender_view_response'
      get 'datewise_question_analytics'
      get 'share_active'
      post 'response_user_info'
      post 'location'
      post 'show_dashboard_wordcloud'
      get 'shift_to_trial_period'
    end
  end

  #admin routes
  namespace :admin do
    resources :pricing_plans
    resources :permissions
    resources :client_settings do
      collection do
        get 'user_client_settings'
      end
    end
    resources :reports do
     collection do
       get 'weekly_report'
       get 'daily_report'
    end
  end
    resources :listeners do
     collection do
       get 'list_listeners'
       get 'request_listner'
       post 'share_listener'
     end
     member do
       get 'activate_listener'
     end
    end
  end

  namespace :api do
    resources :campaigns do
      collection do
       post 'email_blast'
       post 'sms_blast'
      end
    end
  end

  resources :email_activity do
    collection do
      post 'email_track'
    end
  end

  resources :manage_roles 
  #business_customer_infos
  #resources :business_customer_infos
  post "check_business_customer" => "distribute#check_business_customer"
  post "create_business_customer" => "distribute#create_business_customer"

  #~ get '*path' => 'application#invalid_url'
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  layout 'question_response', :only => :show
  before_filter :find_customer_details,:only => [:show_question,:response_question, :response_save, :update_view_count, :embed, :response_embed, :view_count_update,:response_email_verify,:create_user_info]
  before_filter :get_question, except: [:states, :show_embed_survey]
  skip_before_filter :verify_session, only: [:show, :show_question, :embed_survey, :response_save, :response_email_verify, :show_embed_survey, :save_embed_response]
  layout 'prev_question', :only => [:response_email_verify, :create_user_info]
  include SurveyResponse
  include SurveyQuestion
  include SurveyUserDetails
  # layout false
  def show
    @question_status = @question.check_status if @question
    render :layout => "question_response"
  end

  def show_question
    show_survey_question(params)
  end

  def response_save
    unless check_cookie_already_answered(@question.id, params[:provider])
      save_response(params)
    else
      @response = "Error"
    end
  end

  def save_embed_response
    @question = Question.get_question(params[:id])
    embed_response_save_if_not_answered(false, @question)
    @thanks_msg = @question.thanks_response
    respond_to do |format|
      @response = 200
      format.js if request.xhr?
    end
  end



  def response_email_verify
    @user_id = @question.user_id
    @thanks_msg = @question.thanks_response
    @email = params[:email]
    @errors = Question.validate_email(@email) if @email
    response_email_verify_check(params,@question,@cookie_uuid,@errors,params[:already_answered])
    respond_to do |format|
      format.js
    end
  end


  def create_user_info
    @user_id = @question.user_id
    create_info_geo_location_is_active(params,@cookie_uuid,@user_id)
    if @customer.errors.blank?
      update_customer_id_in_logs(@customer)
    else
      @errors = @customer.errors
    end
    respond_to do |format|
      format.js if request.xhr?
      format.html
    end
  end

  def states
    @country = Country[params[:keywords]]
    @states = @country.states
    respond_to do |format|
      format.js
    end
  end

  def embed_survey
    question = Question.get_question(params[:id])
    active_embed_question = Question.where(user_id: question.user_id, embed_status: true, status: "Active").first
    @question = active_embed_question.blank? ? Question.change_embed_status(question.user_id) : active_embed_question
    @question_style = @question.question_style if @question
    @attachment, @company_name, @question_options = @question.embed_question_share
    render :layout => false
  end

  def update_embed_status
    Question.update_embed_status(params[:q_id], current_user.id)
    render :json => {:status => 200}
  end

  def show_embed_survey
    session[:q_v_id], session[:q_r_id], session[:ans_ids] = nil
    params[:provider] = "embed"
    @question = Question.get_question(params[:id])
    if @question.status !="Closed"
      @category_type = CategoryType.all.uniq{|x| x.category_name}.sort
      view_log_id = QuestionViewLog.create_new_record(@question,params[:provider],nil)
      session[:q_v_id] = view_log_id unless view_log_id.nil?
      render :json => {:provider => params[:provider], :question_id => @question.id}
    end
  end

  private

  # Find user details based on the customer ID
  def find_customer_details
    question_id = Question.get_question(params[:id]).id if params[:id]
    if params[:cid].present? && question_id.present?
      customer_id = ActiveSupport::JSON.decode( Base64.decode64(params[:cid]))
      is_answered_already = Answer.check_already_answered(question_id,customer_id, params["provider"])
      customer_cookie_detail = customer_id && !is_answered_already ? params[:cid] : (cookies.signed[:customer_details].present? ? cookies.signed[:customer_details] : '')
    else
      customer_cookie_detail = cookies.signed[:customer_details].present? ? cookies.signed[:customer_details] : ''
    end
    @cookie_uuid = params["cookie_token_value"].present? ? params["cookie_token_value"] : customer_cookie_detail
    @customer_cookie_detail = !customer_cookie_detail.blank? ? BusinessCustomerInfo.get_customer_info(@cookie_uuid) :  ''
  end

  def get_question
    @question= Question.get_question(params[:id])
  end

end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/surveys/_pop_up.html.erb
  <div class="question-dialog-box-wrap">
    <div class="question-dialog-box" id="success_msg">
      <!-- rails4_image_tag_impact --><%= image_tag("thank-u.png", alt: "", class: "fl") %>
      <!-- <img src="/assets/thank-u.png" alt="" class="fl" > -->
      <div class="box-info">
<!--         <h4></h4>
        <p id="success"></p> -->
        <h2 class="thankyou-msg">
          <span class="glyphicon glyphicon-ok-circle"></span>
          <span class="thankmsg" id="success"></span>
        </h2>
      </div>
    </div>
    <br>
    <div class="question-dialog-box answered-msg" id="failure_msg">
      <span class="glyphicon glyphicon-ban-circle"></span>
      <span class="answered">You've already answered this question.
       Your feedback is important to us.Thanks for responding.</span>
     </div>

   </div>
   <div id="form_container">
    <h2 class="header small-text">Fill In Your Email Address</h2>
    <%= form_tag response_email_verify_survey_path, :remote => true ,:id=>"response_email_verify_path" do %>
    <div class="frm-email-field">
      <input type="hidden" value="<%= @cookie_uuid %>" name="cookie_token_value"/>
      <input type="text" name="email" id="email" style="background-color: #F6F6F6;border: 1px solid #AEAEAE;border-radius: 3px 3px 3px 3px;color: #181818;font-size: 14px;font-weight: 700;margin-right: 11px;outline: 0 none;padding: 7px;width: 300px;" placeholder="Enter Your Email" value="<%= params[:email].present? ? params[:email] : ''%>"/>
      <p><span class="error" id='email_error' style='display:none;'></span></p>
      <input type="hidden" value="<%= question_slug %>" name="question_id"/>
      <input type="hidden" value="<%= answer_id %>" id="answer_id_new" name="answer_id"/>
      <input type="hidden" value="<%= provider %>" id="provider" name="provider"/>
    </div>
    <div class="clearfix submit-btn">
      <input class="btn rc_5" id="email_verify" type="submit" value="Submit" name="commit" style="width:125px;"/>
    </div>
    <% end %>
  </div>
  <script type="text/javascript">
        jQuery("#submit1").val('Submit');
        jQuery("#email_verify").click(function(){
            jQuery(this).val('Please wait...');
        });
  </script>

app/views/surveys/create_user_info.html.erb
<%= javascript_include_tag "responsive/page_loaders/dashboard"%>
<div class="question-dialog-box-wrap">
<div class="question-dialog-box" id="success_msg1">
  <!-- rails4_image_tag_impact -->
  <%= image_tag("thank-u.png", alt: "", class: "fl") %>
 <!-- <img src="/assets/thank-u.png" alt="" class="fl" > -->
		<div class="box-info">
				<p id = "sucess_new"></p>
	</div>
</div>
<br>
<div class="question-dialog-box" id="failure_msg">
  <!-- rails4_image_tag_impact -->
  <%= image_tag("stop.png", alt: "", class: "fl") %>
  <!-- <img src="/assets/stop.png" alt="" class="fl" > -->
		<div class="box-info">
				<h4>You've already answered this question.</h4>
				<p>Thanks for responding. Your feedback is important to us.</p>
	</div>
</div>
</div>

app/views/surveys/create_user_info.js.erb
var delay = (function () {
        var timer = 0;
        return function (callback, ms) {
            clearTimeout(timer);
            timer = setTimeout(callback, ms);
        };
    })();
<% if @errors%>
<%if @errors && @errors[:customer_name]%>
	jQuery('#error_fname').show();
	jQuery('#error_fname').html("<%=escape_javascript(@errors[:customer_name][0])%>");
	<% end%>
	<%if @errors && @errors[:mobile]%>
	jQuery('#error_mobile').show();
	jQuery('#error_mobile').html("<%=escape_javascript(@errors[:mobile][0])%>");
    jQuery('#submit_form').attr('disabled', false);
    jQuery('#submit_form').css( 'cursor', 'pointer' );
	<% end%>
	<%if @errors && @errors[:age]%>
	jQuery('#error_age').show();
	jQuery('#error_age').html("<%=escape_javascript(@errors[:age][0])%>");
	<% end%>
	<%if @errors && @errors[:gender]%>
	jQuery('#error_gender').show();
	jQuery('#error_gender').html("<%=escape_javascript(@errors[:gender][0])%>");
	<% end%>
	<%if @errors && @errors[:country]%>
	jQuery('#error_country').show();
	jQuery('#error_country').html("<%=escape_javascript(@errors[:country][0])%>");
	<% end%>
<% else%>
jQuery('#response_user').hide();
//jQuery.isLoading( "hide" );
<%if params[:provider] !="embed"%>
jQuery("#success_msg1").css("margin-right","100px");
jQuery('#submit_form').attr('disabled', true);
jQuery('#submit_form').css( 'cursor', 'not-allowed');
<%end%>
  <%if params["country"].present? && params[:provider] == "embed"%>
      jQuery(".modal-content").css("top","163px");
  <%end%>
jQuery('#success_msg1').show();
thanks_msg = '<%=escape_javascript(@question.thanks_response.gsub("\r\n","!-!-!-!"))%>';
jQuery("#sucess_new").html(GetWrapedText(thanks_msg.replace(/(!-!-!-!)/gm,'<br/>'),40));
<%if params[:provider] !="embed"%>
  jQuery("#response-container").css("height","200px");
  <%end%>
  <%if params[:provider] !="embed"%>

delay(function(){
     $("#response_email_modal").hide();
    $(".modal-backdrop").remove();
    window.location.href = "<%=user_redirect_url%>";
   },5000);
  <%end%>

<%end%>

app/views/surveys/question.js.erb
jQuery('#response_question').html('<%= escape_javascript(render :partial => 'show_partial') %>')

app/views/surveys/response_email_verify.js.erb
<%#= javascript_include_tag "http://maps.googleapis.com/maps/api/js?sensor=false" %>
var delay = (function () {
    var timer = 0;
    return function (callback, ms) {
        clearTimeout(timer);
        timer = setTimeout(callback, ms);
    };
})();
function disable_response(){
    delay(function(){
        $("#response_email_modal").hide();
        $(".modal-backdrop").remove();
        window.location.href = "<%=user_redirect_url%>";
    },5000);
}
 
<% if @errors.present?%>
jQuery("#email_form").val('Submit');
$("#email_form").prop('disabled', false).css('cursor','');
jQuery('#email_error').show();
jQuery("#email_error").html(' <%=escape_javascript(@errors[:email])%>');
  <% if @cookie_result  %>
    var cookie_result = "true";
  <%else%>
    var cookie_result = "false";
  <% end %>
<% else %>
<% if @response == "Success" %> //&&
<% if @view_log_error.blank? || @res_log_error.blank? %>
  thanks_msg = '<%=escape_javascript(@thanks_msg.gsub("\r\n","!-!-!-!"))%>';
  var cookie_result = "false";
	jQuery('#success_msg').show();

	jQuery("#response_email_verify_path").hide();
    jQuery("#success").html(GetWrapedText(thanks_msg.replace(/(!-!-!-!)/gm,'<br/>'),40));
<% else %>
   jQuery("#response_email_verify_path").hide();
   jQuery('#failure_msg').show();
<% end %>
  <%if params[:provider] != 'embed'%>
    disable_response();
    <%end%>
<%elsif @response == "Error"%>
    var cookie_result = "true";
	jQuery("#form_container").html(' ');
	jQuery('#failure_msg').show();
	jQuery(".white_content").css("height","200px");
    disable_response();
<%else%>
	jQuery("#form_container").html("<%= escape_javascript(render :partial => 'dashboard/user_info', :locals => { :question_id => @question.slug, :email => @email, :answer_id => @answer_id}) %>");
<%end%>
<% end%>

app/views/surveys/response_save.html.erb
<!-- TYPEKIT -->
<script type="text/javascript" src="https://use.typekit.com/ltc1ytn.js"></script>
<script type="text/javascript">try{Typekit.load();}catch(e){}</script>
<% benchmark '##Render surveys pop up in response save' do %>
<%= render :partial => "surveys/pop_up",:locals=>{:answer_id=>@answer_id, :question_slug => @question.slug, :provider => @provider} %>
<% end %>

app/views/surveys/save_embed_response.js.erb
<% if @response == 200%>
jQuery("#embed_mock").show();
// This function need to optimize, not loading from the application js due to ajax response
function GetWrapedText(text, maxlength) {
    var resultText = [""];
    var len = text.length;
    if (maxlength >= len) {
        return text;
    }
    else {
        var totalStrCount = parseInt(len / maxlength);
        if (len % maxlength != 0) {
            totalStrCount++
        }

        for (var i = 0; i < totalStrCount; i++) {
            if (i == totalStrCount - 1) {
                resultText.push(text);
            }
            else {
                var strPiece = text.substring(0, maxlength - 1);
                resultText.push(strPiece);
                resultText.push("<br>");
                text = text.substring(maxlength - 1, text.length);
            }
        }
    }
    return resultText.join("");
}
<%end%>

app/views/surveys/show.html.erb
 <div id="response_question">
 <% if @question_status != "Active"%>
<div class="response-wrapper">
  <div class="response-whole-wrapper">
    <div class="response-container">
        <h1 style="font-size:1.4em;color:red;text-align: center;">
          <div class="row">
          <% if (@question && @question.status.downcase == "closed")%>
                <div class="col-xs-12">This question has expired</div>
          <% else (@question && @question.status.downcase =="inactive") %>
                <div class="col-xs-12"> <%= (((@question && !@question.qrcode_status) || (@question && @question.qrcode_status == "")) && params[:provider] == "QR") ? "No question is mapped to QR code." : "This question is inactive" %></div>
          <% end %>
          </div>
        </h1>
    </div>
    </div>
</div>
 <%end%>
</div>

<script>
<%if @question_status == "Active"%>
jQuery.ajax({
        url: '/surveys/show_question',
        type: 'post',
    beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', jQuery('meta[name="csrf-token"]').attr('content'))},
    data: {id:'<%=@question.slug%>',cid: '<%=params[:cid]%>',provider: '<%=params[:provider]%>'},
      dataType : "script"
      });
<%end%>
 </script>

app/views/surveys/show_question.js.erb
var selected_languages = ['<%= @question.language %>'];
<% if (params[:provider] !=  "QR" && @question.status == 'Active') ||  (params[:provider] == "QR" &&  @question.status == 'Active' && @question.qrcode_status && @question.qrcode_status == "Active")  %>
jQuery('#response_question').html('<%= escape_javascript(render :partial => 'show_partial') %>')
<% else %>
jQuery('#response_question').html("<div id='response_question'><div class='response-wrapper'><div class='response-whole-wrapper'><div class='response-container'><h1 style='font-size:1.4em;color:red;text-align: center;'><div class='row'><div class='col-xs-12'>No question is mapped to QR code.</div></div></h1></div></div></div></div>")
<% end %>

app/views/surveys/states.js.erb
jQuery("#states").html('<%=escape_javascript(options_for_select([['Select states', '']]+@states.collect{|key,value| [value["name"],value["name"]]}) )%>');