config/routes.rb
InquirlyNew::Application.routes.draw do

  ActiveAdmin.routes(self)
  match '/about' => "static#about", via: :get
  match '/help' => "static#help", via: :get
  post "/transaction" => "payments#handler"
  post "/response_handler" => "payments#response_handler"
  resources :tenants do
    collection do
      post 'change_tenant_status'
      get 'check_caller_id'
      get 'check_verify_caller_ids'
    end
  end
  resources :corporate_users do
    collection do
     get 'mapping_roles'
     post 'update_user_roles'
     post 'reset_password'
     get 'mapping_tenant'
     put 'update_tenant_users'
     get 'search_tenant_name'
     get 'search_user'
     get 'search_user_by_email'
     post 'change_user_status'
     get 'get_all_user'
    end
  end

  match '/', to: 'home#enterprise_login', constraints: { subdomain: /.+/ }, via: [:get, :post, :put, :patch, :delete]
devise_scope :user do
    authenticated :user do
      root 'dashboard#index', as: :authenticated_root
    end

    unauthenticated :user do
      root  'home#index'
    end
  end
  devise_for :users, :controllers => {sessions: "users/sessions", registrations: "users/registrations", passwords: "users/passwords", omniauth_callbacks: "users/omniauth_callbacks", confirmations: "users/confirmations", unlocks: "users/unlocks"}, :path_names => {sign_in: "login", sign_up: "register"}

  # devise_scope :user do
  #   match "/users/auth/facebook/callback", :to => "users/omniauth_callbacks#facebook", via: :get
  #   match '/users/auth/twitter/callback' => "users/omniauth_callbacks#twitter", via: :get
  #   match '/users/auth/google_oauth2/callback' => "users/omniauth_callbacks#google", via: :get
  #   match '/users/auth/linkedin/callback' => "users/omniauth_callbacks#linkedin", via: :get
  # end

  devise_scope :user do
    match "/users/auth/facebook/callback", :to => "users/omniauth_callbacks#facebook", via: :get
    match '/users/auth/twitter/callback' => "users/omniauth_callbacks#twitter", via: :get
    match '/users/auth/google_oauth2/callback' => "users/omniauth_callbacks#google", via: :get
    match '/users/auth/linkedin/callback' => "users/omniauth_callbacks#linkedin", via: :get
    match 'auth/:provider/failure', :to => "users/omniauth_callbacks#failure", via: :get
    match '/users/confirmation', :to => "users/confirmations#create", :via => :post
    match '/users/confirmation/new', :to => "users/confirmations#new", :via => :get
    match '/users/confirmation', :to => "users/confirmations#show", :via => :get
    match '/users/validate_user', :to => "users/sessions#validate_user_data", :via => :post
  end

  # Import
  resources :imports do
    collection do
    post 'create_customer_info'
    get 'csv_template'
    get 'customer_data'
    end
  end

  resources :payments do
    collection do
    get 'merchant_test'
    post 'post_to_zaakpay'
    post 'z_response'
    post 'send_cancel_email'
    get 'download_success'
    post 'update_billing'
    post 'update_payment_details'
    get 'get_user_plan_details'
    get 'get_user_emails'
    end
  end

#  match "/import_data", :to => "imports#import_data", via: :post
  match "/user_info_list" => "question#user_info_list", via: :get
  # Account
  resources :account do
    collection do
      #get 'upgrade'
      #get 'downgrade'
      get 'change_plan'
      post 'social_login'
      get 'company_settings'
      #put 'update_company_info'
      get 'transaction_history'
      post 'valid_email'
      get 'user_account'
      get 'get_customer_info'
      post 'add_social_account'
      post 'account_attachment'
      get 'profile_header'
    end
  end

#api calls
 get '/transaction_history' => 'account#transaction_history'
 post '/valid_email' => 'account#valid_email'
 get '/get_inquirly_user' => 'home#get_inquirly_user'

  resources :question do
    match '/answer' => "question#answer", via: :get
    member { post 'upload_logo'}
    member { post 'customize'}
    member { post 'generate_bity_url'}
    member { get 'get_style'}
    member { get 'get_image'}
    member { get 'get_detail'}
    member { get 'view_response_by_provider'}
    member { get 'view_response_by_location'}
    member { post 'update_question_status'}
    member { get 'default_settings'}
    get :deactivate
    get :preview
    get :search, :on => :collection
    get :share_question, :on => :collection

    collection do
      get 'index'
      get 'single_question'
      get 'multiple_question'
      get 'yes_no_question'
      get 'comment_question'
      get 'qrcode_active_inactive'
      #get 'default_settings'
      post 'question_status_change'
      post 'question_video_upload', :as => "video_upload"
      get 'sentiment_analyze'
      post 'show_question_wordcloud'
     end
  end

# in web its in get request but in api post
post '/qst_deactivate', :to => 'question#deactivate'
get '/home/signup' => 'home#signup_form'
get '/home/signin' => 'home#signin_form'
get '/home/forgot_password' => 'home#forgot_password_form'
post '/share/filter_converted_leads/:remainder', :to => "share#filter_converted_leads"

  resources :share do
   collection { get 'show' }
   member do
     get 'share_to_social_nw'
     get 'show_sms'
     post 'share_sms'
     get 'show_qr'
     get 'show_embed_code'
     post 'share_email'
     post 'activate_qr'
     get 'show_call_list'
     post 'share_call'
     post 'make_demo_call'
     get 'show_email'
   end
   collection do
   post 'make_call'
   post 'api_qrcode_url'
   get 'social_status_change'
   post 'call_handle'
   get 'handle_gather'
   get 'qrcode_url'
   get 'customers_data_grid'
   get 'qrdownload'
   get 'listeners_page'
   post 'check_customer_limit'
   post 'mandril_report'
   post 'twillo_call_report'
   post 'share_facebook'
   get 'customer_data_collection'
    end
  end


  resources :surveys do
   collection do
     get 'show'
     get 'states'
     post 'show_question'
     get 'update_embed_status'
   end
   member do
     post 'response_save'
     post 'response_email_verify'
     post 'create_user_info'
     get 'embed_survey'
     post 'show_embed_survey'
     post 'save_embed_response'
   end
  end

 resources :downloads do
   collection do
     #get 'download_pdf'
     get 'download_csv'
   end
 end

 resources :customers do
    collection do
    get 'get_customer_email'
    # get 'index'
    # post 'create'
    # put 'update'
    # delete 'destroy'
    get 'email_duplication_check'
    get 'mobile_duplication_check'
    post 'delete_selected'
    post 'remove_social_account'
    end
 end

 resources :answers do
  collection do
    #get 'sentiment_analyze'
    get 'report'
  end
 end


  get 'fill_sugg_qst' => 'question#fill_sugg_qst'

  resources :dashboard, :only => [:index] do
    collection do
      get 'social_media_analytics'
      get 'get_customers_by_location'
      get 'total_gender_view_response'
      get 'datewise_question_analytics'
      get 'share_active'
      post 'response_user_info'
      post 'location'
      post 'show_dashboard_wordcloud'
      get 'shift_to_trial_period'
    end
  end

  #admin routes
  namespace :admin do
    resources :pricing_plans
    resources :permissions
    resources :client_settings do
      collection do
        get 'user_client_settings'
      end
    end
    resources :reports do
     collection do
       get 'weekly_report'
       get 'daily_report'
    end
  end
    resources :listeners do
     collection do
       get 'list_listeners'
       get 'request_listner'
       post 'share_listener'
     end
     member do
       get 'activate_listener'
     end
    end
  end

  namespace :api do
    resources :campaigns do
      collection do
       post 'email_blast'
       post 'sms_blast'
      end
    end
  end

  resources :email_activity do
    collection do
      post 'email_track'
    end
  end

  resources :manage_roles 
  #business_customer_infos
  #resources :business_customer_infos
  post "check_business_customer" => "distribute#check_business_customer"
  post "create_business_customer" => "distribute#create_business_customer"

  #~ get '*path' => 'application#invalid_url'
end

app/controllers/admin/reports_controller.rb
#~ require 'csv'
#~ class Admin::ReportsController < ApplicationController
  #~ layout 'admin_layout'
  #~ before_filter :check_user

  #~ def dashboard
  #~ end

  #~ def weekly_report
    #~ report_weekly_daily
    #~ if (params[:csv] == "true" && params[:top_three_questions_csv])
      #~ csv_string = CSV.generate do |csv|
        #~ csv << ["Question", "Views", "Responses"]
        #~ @questions.each do |q|
          #~ csv << [q.question, q.question_view_counts.count, q.answers.count]
        #~ end
      #~ end
      #~ send_data csv_string,
        #~ :type => 'text/csv; charset=iso-8859-1; header=present',
        #~ :disposition => "attachment; filename=top_three_questions_report.csv"
    #~ end
  #~ end

  #~ def daily_report
    #~ report_daily_report
    #~ csv_file_name = ''
    #~ array_of_questions = ''
    #~ if (params[:csv] == "true" && params[:questions_csv])
      #~ header = ["Question", "Views", "Responses"]
      #~ array_of_questions = @questions
      #~ csv_file_name = "questions_report.csv"
    #~ elsif  (params[:csv] == "true" && params[:todays_sign_ins_csv])
      #~ header = ["CompanyName", "Firstname", "LastName", "Email"]
      #~ array_of_questions = @todays_sign_ins
      #~ csv_file_name = "todays_signins_report.csv"
    #~ elsif  (params[:csv] == "true" && params[:users_sign_ups])
      #~ header = ["Companyname", "Username", "Email"]
      #~ array_of_questions = @users_sign_ups
      #~ csv_file_name = "todays_signups_report.csv"
    #~ elsif  (params[:csv] == "true" && params[:active_questions])
      #~ header = ["Question", "Views", "Responses"]
      #~ array_of_questions =  @active_questions
      #~ csv_file_name = "active_questions_report.csv"
    #~ end
    #~ csv_string = generete_csv(array_of_questions,header,params)
    #~ send_data csv_string,
      #~ :type => 'text/csv; charset=iso-8859-1; header=present',
      #~ :disposition => "attachment; filename=#{csv_file_name}"
  #~ end

  #~ def generete_csv(array_of_questions,header,params)
    #~ csv_string = CSV.generate do |csv|
      #~ csv << header
      #~ array_of_questions.each do |t|
        #~ csv << [t["company_name"], t["first_name"], t["last_name"], t["email"]] if params[:todays_sign_ins_csv].present?
        #~ csv << [t.question, t.question_view_counts.count, t.answers.count] if params[:questions_csv].present? || params[:active_questions].present?
        #~ csv << [t["company_name"], [t["first_name"]+t["last_name"]], t["email"]] if params[:users_sign_ups].present?        
      #~ end
    #~ end
    #~ return csv_string
  #~ end

  #~ #Cron job for weekly reports
  #~ def weekly_reports
    #~ report_weekly_daily
    #~ @email = 'shiva.r547@gmail.com'
    #~ ReportMailer.weekly_reports(@email, @top_three_questions, @Feedback_qustions, @Marketing_qustions, @Innovation_qustions).deliver
  #~ end

  #~ #Cron job for daily reports
  #~ def daily_reports
    #~ report_daily_report
    #~ @email = 'shiva.r547@gmail.com'
    #~ ReportMailer.daily_reports(@email, @todays_sign_ins, @users_sign_ups, @active_questions, @transactions).deliver
  #~ end

  #~ def report_weekly_daily
    #~ # Top 3 questions which are have more responces.
    #~ @top_three_questions = []
    #~ @top_three_questions_hash = []
    #~ @questions = Question.all
    #~ @questions = @questions.sort! { |a, b| b.answers.count <=> a.answers.count }
    #~ @questions = @questions[0..2].each do |q|
      #~ @top_three_questions << q
      #~ @User_details = User.find_by_id(q.user_id)
      #~ @top_three_questions_hash << {"user_name" => (@User_details&&@User_details.first_name.present?) ? @User_details.first_name : "", "question" => q.question, "view_count" => q.question_view_counts.count, "responce_count" => q.answers.count}
    #~ end
    #~ # Top 3 companies which are have more responces.
    #~ @top_companies= []
    #~ @top_three_questions.each do |t|
      #~ @User_detail = User.find_by_id(t.user_id)
      #~ @top_companies << {"company_name" => (@User_detail && @User_detail.company_name.present?) ? @User_detail.company_name : "", "question" => t.question, "view_count" => t.question_view_counts.count, "responce_count" => t.question_options.count}
    #~ end
    #~ # Percentage breack down based on Category Type.
    #~ @category = CategoryType.all.uniq_by{|x| x.category_name}
    #~ @percentage_breack_down_users = Question.joins(:user).where("users.business_type_id = ?", 2).all
    #~ @Feedback_qustions = @percentage_breack_down_users.select { |question| question.category_type_id == @category[0].id }.count
    #~ @Marketing_qustions = @percentage_breack_down_users.select { |question| question.category_type_id == @category[1].id }.count
    #~ @Innovation_qustions = @percentage_breack_down_users.select { |question| question.category_type_id == @category[2].id }.count
  #~ end

  #~ def report_daily_report
    #~ today = Date.today
    #~ @questions = Question.where("created_at >= ?", today)
    #~ @questions_array = []
    #~ @active_questions_array =[]
    #~ @questions = @questions.each do |q|
      #~ @User_details = User.find_by_id(q.user_id)
      #~ @questions_array << {"user_name" => (@User_details && @User_details.first_name.present?) ? @User_details.first_name : "", "question" => q.question, "view_count" => q.question_view_counts.count, "responce_count" => q.answers.count}
    #~ end
    #~ @todays_sign_ins = User.where("current_sign_in_at >= ?", today)
    #~ @users_sign_ups = User.where("created_at >= ?", today)
    #~ @active_questions = Question.where("status == Active" && "updated_at >= ?", today)
    #~ @active_questions.each do |q1|
      #~ @User_detail = User.find_by_id(q1.user_id)
      #~ @active_questions_array << {"user_name" => (@User_detail && @User_detail.first_name.present?) ? @User_detail.first_name : "", "question" => q1.question, "view_count" => q1.question_view_counts.count, "responce_count" => q1.answers.count}
    #~ end
    #~ @transactions = TransactionDetail.where("created_at >= ?", today)
  #~ end

  #~ def check_user
    #~ if current_user && current_user.admin == false
      #~ flash[:non_fade_notice] = "You are not authorized to access admin details."
      #~ redirect_to '/dashboard'
    #~ end
  #~ end
#~ end

app/helpers/admin/reports_helper.rb
module Admin::ReportsHelper
    def response_count(question_id)
    Answer.where(:question_id => question_id ).count
    end
end

app/views/admin/reports/daily_report.html.erb
<div class="wrap-box-head clearfix">
  <h2>Dailly Reports</h2>
</div>
<div class="wrap-box-cont">
  <% content_for :title, "Daily Report" %>
  <div class="white-box-wrapper">
    <div class="box-head clearfix">
      <h3><span class="glyphicon glyphicon-pencil"></span>Questions created by today</h3>
    </div>
    <div class="white-box">
      <%#= @todays_sign_ins.inspect %>
      <%if @questions_array.present? %>
      <div class="form-head clearfix">
        <div class="pull-right">
          <%= link_to '<span class="glyphicon  glyphicon-circle-arrow-down"></span> Download top 3 Questions CSV'.html_safe, daily_report_admin_reports_path(:csv=>true, :questions_csv => @questions), :confirm => "Are you want to download?", :title => "Download report as CSV", :class => "primary-link" %>
        </div>
      </div>
      <% end %>
      <div class="question-table user-list created-quest-list" id="flip-scroll">
        <table class="table-bordered table-striped table-condensed cf">
          <thead class="cf">
            <tr>
              <th class="cl1">
                <div class="qcatg">
                  <span class="glyphicon glyphicon-question-sign"></span>
                </div>
              </th>
              <th class="cl2">Questions</th>
              <th class="cl3">User Name</th>
              <th class="cl4">Views<a href="#"><span class="glyphicon glyphicon-chevron-down"></span></a></th>
              <th class="cl5">Response<a href="#"><span class="glyphicon glyphicon-chevron-down"></span></a></th>
            </tr>
          </thead>
          <tbody>
            <%if @questions_array.present? %>
            <% @questions_array.each do |q| %>
            <tr>
              <td class="td-cat">
                <div class="qcatg">
                   <span class="glyphicon glyphicon-bullhorn"></span>
                </div>
              </td>
              <td class="col-name">
                <%if  q["question"].present? %>
                <%= q["question"] %>
                <%else %>
                No question<% end %>
              </td>
              <td class="col-name">
                <%= q["user_name"] %>
              </td>
              <td>
                <span class="glyphicon glyphicon-eye-open"></span><%= q["view_count"] %>
              </td>
              <td>
                <span class="glyphicon glyphicon-comment"></span><%= q["responce_count"] %>
              </td>
            </tr>
            <% end %>
            <% else %>
            <tr>
              <td colspan="5">
                <div class="alert">
                  <strong>No questions were created</strong>
                </div>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>

    </div>
  </div>
  <!--// Questions created by today -->

  <div class="white-box-wrapper">
    <div class="box-head clearfix">
      <h3><span class="glyphicon glyphicon-user"></span>Today sign in Users list by today</h3>
    </div>
    <div class="white-box">
      <%#= @todays_sign_ins.inspect %>
      <%if @todays_sign_ins.present? %>
      <div class="form-head clearfix">
        <div class="pull-right">
          <%= link_to '<span class="glyphicon  glyphicon-circle-arrow-down"></span> Click here to today\'s signins csv'.html_safe,daily_report_admin_reports_path(:csv=>true, :todays_sign_ins_csv => @todays_sign_ins), :confirm => "Are you want to download?", :title => "Download report as CSV" %>
        </div>
      </div>
      <% end %>
      <div class="question-table user-list new-signup-list" id="flip-scroll">
        <table class="table-bordered table-striped table-condensed cf">
          <thead class="cf">
            <tr>
              <th class="cl1">Company Name</th>
              <th class="cl2">User name</th>
              <th class=""cl3>Email</th>
            </tr>
          </thead>
          <tbody>
            <%if @todays_sign_ins.present? %>
            <% @todays_sign_ins.each do |t| %>
            <tr>
              <td class="col-name">
                <%if t.company_name.present? %>
                <%= t.company_name %>
                <%else%>
                <span class="no-data">No Company Name</span>
                <%end%>
              </td>
              <td class="col-name">
                <%= t.first_name %>
                <%= t.last_name %>
              </td>
              <td class="col-email">
                <%= t.email %>
              </td>
            </tr>
            <% end %>
            <% else %>
            <tr>
              <td colspan="4">
                <div class="alert">
                  <strong>No user sign ins.</strong>
                </div>
              </td>
            </tr>
            <% end %>
          </tbody>
      </table>
      </div>
    </div>
  </div>
  <!--// end. Today sign in Users list by today -->

  <div class="white-box-wrapper">
    <div class="box-head clearfix">
      <h3><span class="glyphicon glyphicon-user"></span>Today sign up Users list by today</h3>
    </div>
    <div class="white-box">
      <%#= @todays_sign_ins.inspect %>
      <%if @users_sign_ups.present? %>
      <div class="form-head clearfix">
        <div class="pull-right">
          <%= link_to '<span class="glyphicon glyphicon-circle-arrow-down"></span> Download today\'s signups CSV'.html_safe, daily_report_admin_reports_path(:csv=>true, :users_sign_ups => @users_sign_ups), :confirm => "Are you want to download?", :title => "Download report as CSV" %>
        </div>
      </div>
      <% end %>
      <div class="question-table user-list new-signup-list" id="flip-scroll">
        <table class="table-bordered table-striped table-condensed cf">
          <thead class="cf">
            <tr>
              <th class="cl1">Company Name</th>
              <th class="cl2">User name</th>
              <th class="cl3">Email</th>
            </tr>
          </thead>
          <tbody>
            <%if @users_sign_ups.present? %>
            <% @users_sign_ups.each do |t| %>
            <tr>
              <td class="col-name">
                <%if t.company_name.present? %>
                <%= t.company_name %>
                <%else%>
                <span class="no-data">No Company Name</span>
                <%end%>
              </td>
              <td class="col-name">
                <%= t.first_name %>
                <%= t.last_name %>
              </td>
              <td class="col-email">
                <%= t.email %>
              </td>
            </tr>
            <% end %>
            <% else %>
            <tr>
              <td colspan="3">
                <div class="alert">
                  <strong>No user signups.</strong>
                </div>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <!--// end. Today sign in Users list by today -->

  <div class="white-box-wrapper">
    <div class="box-head clearfix">
      <h3><span class="glyphicon glyphicon-ok-circle"></span>Activated Questions</h3>
    </div>
    <div class="white-box">
    <%#= @todays_sign_ins.inspect %>
    <%if @active_questions_array.present? %>
      <div class="form-head clearfix">
        <div class="pull-right">
          <%= link_to '<span class="glyphicon glyphicon-circle-arrow-down"></span> Download Active Questions CSV'.html_safe, daily_report_admin_reports_path(:csv=>true, :active_questions => @active_questions), :confirm => "Are you want to download?", :title => "Download report as CSV" %>
        </div>
      </div>
    <% end %>
      <div class="question-table user-list active-users" id="flip-scroll">
      <table class="table-bordered table-striped table-condensed cf">
        <thead class="cf">
          <tr>
            <th class="cl1">
              <div class="qcatg">
                <span class="glyphicon glyphicon-question-sign"></span>
              </div>
            </th>
            <th class="cl2 quescol">Questions</th>
            <th class="cl3 col-name">User Name</th>
            <th class="cl4">Views<a href="#"><span class="glyphicon glyphicon-chevron-down"></span></a></th>
            <th class="cl4">Response<a href="#"><span class="glyphicon glyphicon-chevron-down"></span></a></th>
          </tr>
        </thead>
        <tbody>
          <%if @active_questions_array.present? %>
          <% @active_questions_array.each do |q| %>
          <tr>
            <td class="td-cat">
              <div class="qcatg">
                 <span class="glyphicon glyphicon-bullhorn"></span>
              </div>
            </td>
            <td class="col-name">
              <%if  q["question"].present? %>
              <%= q["question"] %>
              <%else %>
              <span class="no-data">No question</span>
              <% end %>
            </td>
            <td class="col-name">
              <%= q["user_name"] %>
            </td>
            <td>
              <span class="glyphicon glyphicon-eye-open"></span><%= q["view_count"] %>
            </td>
            <td>
              <span class="glyphicon glyphicon-comment"></span><%= q["responce_count"] %>
            </td>
          </tr>
          <% end %>
          <% else %>
          <tr>
            <td colspan="5">
              <div class="alert">
                <strong>No questions were created</strong>
              </div>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    </div>
  </div>

  <!--<h1> Transactions by today </h1>-->
  <%# @transactions.each do |q| %>
  <%#= q.id %>
  <%# end %>
</div>

app/views/admin/reports/dashboard.html.erb
<ul>
<li><%= link_to "WeeklyReport", reports_weekly_report_path %></li>
<li><%= link_to "DailyReport", reports_daily_report_path %></li>
</ul>