config/routes.rb
InquirlyNew::Application.routes.draw do

  ActiveAdmin.routes(self)
  match '/about' => "static#about", via: :get
  match '/help' => "static#help", via: :get
  post "/transaction" => "payments#handler"
  post "/response_handler" => "payments#response_handler"
  resources :tenants do
    collection do
      post 'change_tenant_status'
      get 'check_caller_id'
      get 'check_verify_caller_ids'
    end
  end
  resources :corporate_users do
    collection do
     get 'mapping_roles'
     post 'update_user_roles'
     post 'reset_password'
     get 'mapping_tenant'
     put 'update_tenant_users'
     get 'search_tenant_name'
     get 'search_user'
     get 'search_user_by_email'
     post 'change_user_status'
     get 'get_all_user'
    end
  end

  match '/', to: 'home#enterprise_login', constraints: { subdomain: /.+/ }, via: [:get, :post, :put, :patch, :delete]
devise_scope :user do
    authenticated :user do
      root 'dashboard#index', as: :authenticated_root
    end

    unauthenticated :user do
      root  'home#index'
    end
  end
  devise_for :users, :controllers => {sessions: "users/sessions", registrations: "users/registrations", passwords: "users/passwords", omniauth_callbacks: "users/omniauth_callbacks", confirmations: "users/confirmations", unlocks: "users/unlocks"}, :path_names => {sign_in: "login", sign_up: "register"}

  # devise_scope :user do
  #   match "/users/auth/facebook/callback", :to => "users/omniauth_callbacks#facebook", via: :get
  #   match '/users/auth/twitter/callback' => "users/omniauth_callbacks#twitter", via: :get
  #   match '/users/auth/google_oauth2/callback' => "users/omniauth_callbacks#google", via: :get
  #   match '/users/auth/linkedin/callback' => "users/omniauth_callbacks#linkedin", via: :get
  # end

  devise_scope :user do
    match "/users/auth/facebook/callback", :to => "users/omniauth_callbacks#facebook", via: :get
    match '/users/auth/twitter/callback' => "users/omniauth_callbacks#twitter", via: :get
    match '/users/auth/google_oauth2/callback' => "users/omniauth_callbacks#google", via: :get
    match '/users/auth/linkedin/callback' => "users/omniauth_callbacks#linkedin", via: :get
    match 'auth/:provider/failure', :to => "users/omniauth_callbacks#failure", via: :get
    match '/users/confirmation', :to => "users/confirmations#create", :via => :post
    match '/users/confirmation/new', :to => "users/confirmations#new", :via => :get
    match '/users/confirmation', :to => "users/confirmations#show", :via => :get
    match '/users/validate_user', :to => "users/sessions#validate_user_data", :via => :post
  end

  # Import
  resources :imports do
    collection do
    post 'create_customer_info'
    get 'csv_template'
    get 'customer_data'
    end
  end

  resources :payments do
    collection do
    get 'merchant_test'
    post 'post_to_zaakpay'
    post 'z_response'
    post 'send_cancel_email'
    get 'download_success'
    post 'update_billing'
    post 'update_payment_details'
    get 'get_user_plan_details'
    get 'get_user_emails'
    end
  end

#  match "/import_data", :to => "imports#import_data", via: :post
  match "/user_info_list" => "question#user_info_list", via: :get
  # Account
  resources :account do
    collection do
      #get 'upgrade'
      #get 'downgrade'
      get 'change_plan'
      post 'social_login'
      get 'company_settings'
      #put 'update_company_info'
      get 'transaction_history'
      post 'valid_email'
      get 'user_account'
      get 'get_customer_info'
      post 'add_social_account'
      post 'account_attachment'
      get 'profile_header'
    end
  end

#api calls
 get '/transaction_history' => 'account#transaction_history'
 post '/valid_email' => 'account#valid_email'
 get '/get_inquirly_user' => 'home#get_inquirly_user'

  resources :question do
    match '/answer' => "question#answer", via: :get
    member { post 'upload_logo'}
    member { post 'customize'}
    member { post 'generate_bity_url'}
    member { get 'get_style'}
    member { get 'get_image'}
    member { get 'get_detail'}
    member { get 'view_response_by_provider'}
    member { get 'view_response_by_location'}
    member { post 'update_question_status'}
    member { get 'default_settings'}
    get :deactivate
    get :preview
    get :search, :on => :collection
    get :share_question, :on => :collection

    collection do
      get 'index'
      get 'single_question'
      get 'multiple_question'
      get 'yes_no_question'
      get 'comment_question'
      get 'qrcode_active_inactive'
      #get 'default_settings'
      post 'question_status_change'
      post 'question_video_upload', :as => "video_upload"
      get 'sentiment_analyze'
      post 'show_question_wordcloud'
     end
  end

# in web its in get request but in api post
post '/qst_deactivate', :to => 'question#deactivate'
get '/home/signup' => 'home#signup_form'
get '/home/signin' => 'home#signin_form'
get '/home/forgot_password' => 'home#forgot_password_form'
post '/share/filter_converted_leads/:remainder', :to => "share#filter_converted_leads"

  resources :share do
   collection { get 'show' }
   member do
     get 'share_to_social_nw'
     get 'show_sms'
     post 'share_sms'
     get 'show_qr'
     get 'show_embed_code'
     post 'share_email'
     post 'activate_qr'
     get 'show_call_list'
     post 'share_call'
     post 'make_demo_call'
     get 'show_email'
   end
   collection do
   post 'make_call'
   post 'api_qrcode_url'
   get 'social_status_change'
   post 'call_handle'
   get 'handle_gather'
   get 'qrcode_url'
   get 'customers_data_grid'
   get 'qrdownload'
   get 'listeners_page'
   post 'check_customer_limit'
   post 'mandril_report'
   post 'twillo_call_report'
   post 'share_facebook'
   get 'customer_data_collection'
    end
  end


  resources :surveys do
   collection do
     get 'show'
     get 'states'
     post 'show_question'
     get 'update_embed_status'
   end
   member do
     post 'response_save'
     post 'response_email_verify'
     post 'create_user_info'
     get 'embed_survey'
     post 'show_embed_survey'
     post 'save_embed_response'
   end
  end

 resources :downloads do
   collection do
     #get 'download_pdf'
     get 'download_csv'
   end
 end

 resources :customers do
    collection do
    get 'get_customer_email'
    # get 'index'
    # post 'create'
    # put 'update'
    # delete 'destroy'
    get 'email_duplication_check'
    get 'mobile_duplication_check'
    post 'delete_selected'
    post 'remove_social_account'
    end
 end

 resources :answers do
  collection do
    #get 'sentiment_analyze'
    get 'report'
  end
 end


  get 'fill_sugg_qst' => 'question#fill_sugg_qst'

  resources :dashboard, :only => [:index] do
    collection do
      get 'social_media_analytics'
      get 'get_customers_by_location'
      get 'total_gender_view_response'
      get 'datewise_question_analytics'
      get 'share_active'
      post 'response_user_info'
      post 'location'
      post 'show_dashboard_wordcloud'
      get 'shift_to_trial_period'
    end
  end

  #admin routes
  namespace :admin do
    resources :pricing_plans
    resources :permissions
    resources :client_settings do
      collection do
        get 'user_client_settings'
      end
    end
    resources :reports do
     collection do
       get 'weekly_report'
       get 'daily_report'
    end
  end
    resources :listeners do
     collection do
       get 'list_listeners'
       get 'request_listner'
       post 'share_listener'
     end
     member do
       get 'activate_listener'
     end
    end
  end

  namespace :api do
    resources :campaigns do
      collection do
       post 'email_blast'
       post 'sms_blast'
      end
    end
  end

  resources :email_activity do
    collection do
      post 'email_track'
    end
  end

  resources :manage_roles 
  #business_customer_infos
  #resources :business_customer_infos
  post "check_business_customer" => "distribute#check_business_customer"
  post "create_business_customer" => "distribute#create_business_customer"

  #~ get '*path' => 'application#invalid_url'
end

app/models/pricing_plan.rb
class PricingPlan < ActiveRecord::Base
after_create :assign_business_type_id
after_save :reload_pricing_plan_initializer
has_many :pricing_category_types
has_many :category_types, :through => :pricing_category_types

PRICING_PLAN_EXD_COLUMNS = ["id","created_at","updated_at","plan_name","expired_date"]
PRICING_PLAN_COLUMNS = self.column_names if self.table_exists?

def self.define_pricing_plans
@pricing_plans = {}
plans = self.get_all_plans
plans.find_each do |plan|
PRICING_PLAN_COLUMNS.each do |column|
 @pricing_plans.merge!({"#{plan.plan_name}:#{column}" => plan.send("#{column}") })  unless PRICING_PLAN_EXD_COLUMNS.include?(column)
end
 @pricing_plans.merge!({"#{plan.plan_name}:category_types" => plan.category_types.map(&:id)})
end
return @pricing_plans
end

def self.get_all_plans
  self.where("expired_date is null")
end

def self.list_all_plans
  self.all
end

def self.get_settings_plans
  self.where("expired_date is null and id > ?",1)
end


#order_by_amount, start from large amount
def self.order_by_amount
  self.get_all_plans.order("amount DESC")
end

#order_by_amount, start from small amount
def self.order_by_amount_asc
  self.get_all_plans.order("amount ASC")
end

#change plan checking
def self.change_plan_check(current_plan_id,new_plan_id)
  current_plan = self.find_by_business_type_id(current_plan_id)
  new_plan = self.find_by_business_type_id(new_plan_id)
    if current_plan.id == new_plan.id
    return "current_plan"
  elsif new_plan.amount > current_plan.amount
    return "upgrade"
  elsif  new_plan.amount < current_plan.amount
    return "downgrade"
  end
end

def self.find_pricing_plan(id)
  where(id: id)
end

private
def assign_business_type_id
   self.update_attribute("business_type_id",self.id)
end

def reload_pricing_plan_initializer
   ActiveSupport::Dependencies.load_file "config/initializers/pricing_plan.rb"
end

end

app/controllers/admin/pricing_plans_controller.rb
class Admin::PricingPlansController < InheritedResources::Base
  #before_filter :check_admin,:except => ["request_listener"]
  before_filter :check_role_level_permissions
  before_filter :authenticate_user_web_api
  layout 'pricing_plan'

  # GET /pricing_plans
  # GET /pricing_plans.json
  def index
    @pricing_plans = PricingPlan.list_all_plans.paginate(:page => params[:page], :per_page => 10)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pricing_plans }
    end
  end

  # GET /pricing_plans/1
  # GET /pricing_plans/1.json
  def show
    @pricing_plan = PricingPlan.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pricing_plan }
    end
  end

  # GET /pricing_plans/new
  # GET /pricing_plans/new.json
  def new
    @pricing_plan = PricingPlan.new
    @category_types = CategoryType.all
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pricing_plan }
    end
  end

  # GET /pricing_plans/1/edit
  def edit
    @category_types = CategoryType.all
    @pricing_plan = PricingPlan.find(params[:id])
  end

  # POST /pricing_plans
  # POST /pricing_plans.json
  def create
    @pricing_plan = PricingPlan.new(pricing_params)
    respond_to do |format|
      if @pricing_plan.save
        format.html { redirect_to [:admin, @pricing_plan], notice: 'Pricing plan was successfully created.' }
        format.json { render json: @pricing_plan, status: :created, location: @pricing_plan }
      else
        format.html { render action: "new" }
        format.json { render json: @pricing_plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pricing_plans/1
  # PUT /pricing_plans/1.json
  def update
    @pricing_plan = PricingPlan.find(params[:id])
    respond_to do |format|
      if @pricing_plan.update_attributes(pricing_params)
        format.html { redirect_to [:admin, @pricing_plan], notice: 'Pricing plan successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pricing_plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pricing_plans/1
  # DELETE /pricing_plans/1.json

  # def destroy
  #   @pricing_plan = PricingPlan.find(params[:id])
  #   @pricing_plan.destroy

  #   respond_to do |format|
  #     format.html { redirect_to pricing_plans_url }
  #     format.json { head :no_content }
  #   end
  # end


private

def pricing_params
  params.require(:pricing_plan).permit(:listener,:expired_date,:questions_count,:video_photo_count,:email_count,:sms_count,:call_count,:question_suggestions,:qr_share,:social_share,:embed_share,:plan_name, :business_type_id,:tenant_count,:customer_records_count,:language_count,:redirect_url,:from_number, :crawler_slots, :listener_slots, :email_alerts, :amount,category_type_ids: [])
end

  def check_admin
    if !current_user.blank?
    admin_true = User.where(id: current_user.id, admin: true)
    if admin_true.blank?
      flash[:notice] = "#{APP_MSG['authorization']['failure']}"
      redirect_to "/"
    end
    else
      flash[:notice] = "#{APP_MSG['authorization']['failure']}"
      redirect_to "/"
    end
  end

end

app/helpers/pricing_plans_helper.rb
module PricingPlansHelper
end

app/views/admin/pricing_plans/_form.html.erb
<%= form_for [:admin, @pricing_plan] do |f| %>
  <% if @pricing_plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pricing_plan.errors.count, "error") %> prohibited this pricing_plan from being saved:</h2>

      <ul>
      <% @pricing_plan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :plan_name %><br>
    <%= f.text_field :plan_name %>
  </div>
  <!--<div class="field">
    <%#= f.label :business_type_id %><br>
    <%#= f.number_field :business_type_id %>
  </div>-->
  <%unless @pricing_plan.business_type_id%>
  <input type='hidden' name='pricing_plan[business_type_id]' value='1'/>
  <%end%>
  <div class="field">
    <%= f.label :tenant_count %><br>
    <%= f.number_field :tenant_count %>
  </div>
  <div class="field">
    <%= f.label :customer_records_count %><br>
    <%= f.number_field :customer_records_count %>
  </div>
  <div class="field">
    <%= f.label :category_type_id %><br>
    <%#= f.text_field :category_type_ids %>
   <%=select_tag 'pricing_plan[category_type_ids][]', options_for_select(
@category_types.map {|category| [category.category_name,category.id]}), :multiple => true%>
  </div>

  <div class="field">
    <%= f.label :language_count %><br>
    <%= f.number_field :language_count %>
  </div>

    <div class="field">
    <%= f.label :questions_count %><br>
    <%= f.number_field :questions_count %>
  </div>
    <div class="field">
    <%= f.label :video_photo_count %><br>
    <%= f.number_field :video_photo_count %>
  </div>

     <div class="field">
    <%= f.label :email_count %><br>
    <%= f.number_field :email_count %>
  </div>
       <div class="field">
    <%= f.label :sms_count %><br>
    <%= f.number_field :sms_count %>
  </div>
       <div class="field">
    <%= f.label :call_count %><br>
    <%= f.number_field :call_count %>
  </div>
   <div class="field">
     <%= f.label :question_suggestions %><br>
     <%=f.check_box :question_suggestions%>
  </div>
     <div class="field">
     <%= f.label :qr_share %><br>
     <%=f.check_box :qr_share%>
  </div>
     <div class="field">
     <%= f.label :social_share %><br>
     <%=f.check_box :social_share%>
  </div>
  <div class="field">
     <%= f.label :embed_share %><br>
     <%=f.check_box :embed_share%>
  </div>
	  <div class="field">
     <%= f.label :amount %><br>
     <%=f.text_field :amount%>
    </div>
    <div class="field">
     <%= f.label :listener %><br>
     <%=f.check_box :listener%>
  </div>
    <div class="field">
      <%= f.label :redirect_url %><br>
      <%=f.check_box :redirect_url%>
    </div>
    <div class="field">
      <%= f.label :from_number %><br>
      <%=f.check_box :from_number%>
    </div>
    <div class="field">
      <%= f.label :listener_slots %><br>
      <%=f.text_field :listener_slots%>
    </div>
    <div class="field">
      <%= f.label :crawler_slots %><br>
      <%=f.text_field :crawler_slots%>
    </div>
    <div class="field">
      <%= f.label :email_alerts %><br>
      <%=f.check_box :email_alerts%>
    </div>
  <div class="field">
     <%= f.label :expired_date %><br>
     Note: set the expiry date if you deactivate the plan
            <div class="date-picker">
     <%=f.text_field :expired_date,:class=>"form-control date datepicker fliter-from-date",:id=>"expired_date",:readonly=>true,:value=>""%>
   </div>
  </div>
   <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<script type="text/javascript">
 $("#expired_date").datepicker({
      showOn : "button",
      buttonImage : "/assets/responsive/calendar.png",
      buttonImageOnly : true,
      dateFormat : 'yy/mm/dd',
    minDate: new Date()
});
</script>

app/views/admin/pricing_plans/edit.html.erb
<h1>Editing pricing_plan</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_pricing_plan_path(@pricing_plan) %> |
<%= link_to 'Back', admin_pricing_plans_path %>

app/views/admin/pricing_plans/index.html.erb
<h1>Listing pricing_plans</h1>

<table>
  <thead>
    <tr>
      <th>Plan name</th>
      <th>Business type</th>
      <th>Tenant count</th>
      <th>Customer records count</th>
      <th>Category type ids</th>
      <th>Language count</th>
      <th>Listener</th>
      <th>Expired date</th>
      <th>Amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pricing_plans.each do |pricing_plan| %>
      <tr>
        <td><%= pricing_plan.plan_name %></td>
        <td><%= pricing_plan.business_type_id %></td>
        <td><%= pricing_plan.tenant_count %></td>
        <td><%= pricing_plan.customer_records_count %></td>
        <td><%= pricing_plan.category_type_ids %></td>
        <td><%= pricing_plan.language_count %></td>
        <td><%= pricing_plan.listener%></td>
        <td><%= pricing_plan.expired_date %></td>
        <td><%= pricing_plan.amount %></td>
        <td><%= link_to 'Show', admin_pricing_plan_path(pricing_plan) %></td>
        <td><%= link_to 'Edit', edit_admin_pricing_plan_path(pricing_plan) %></td>
        <td><%#= link_to 'Destroy', admin_pricing_plan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>

</table>

<br>
      <div class="row">
    <div class="pull-right">

     <%= will_paginate @pricing_plans, renderer: BootstrapPagination::Rails %>
     </div>
     </div>

<%= link_to 'New Pricing plan', new_admin_pricing_plan_path %>

app/views/admin/pricing_plans/new.html.erb
<h1>New pricing_plan</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_pricing_plans_path %>

app/views/admin/pricing_plans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Plan name:</strong>
  <%= @pricing_plan.plan_name %>
</p>

<p>
  <strong>Business type:</strong>
  <%= @pricing_plan.business_type_id %>
</p>

<p>
  <strong>Tenant count:</strong>
  <%= @pricing_plan.tenant_count %>
</p>


<p>
  <strong>Category types:</strong>
  <%= @pricing_plan.category_types.map(&:category_name) %>
</p>

<p>
  <strong>Language count:</strong>
  <%= @pricing_plan.language_count %>
</p>

<p>
  <strong>Questions count:</strong>
  <%= @pricing_plan.questions_count %>
</p>
<p>
  <strong>Video Photo count:</strong>
  <%= @pricing_plan.video_photo_count %>
</p>
<p>
  <strong>Customer Records count:</strong>
  <%= @pricing_plan.customer_records_count %>
</p>
<p>
  <strong>Email count:</strong>
  <%= @pricing_plan.email_count %>
</p>
<p>
  <strong>Sms count:</strong>
  <%= @pricing_plan.sms_count %>
</p>
<p>
  <strong>Call count:</strong>
  <%= @pricing_plan.call_count %>
</p>

<p>
  <strong>Question suggestions:</strong>
  <%= @pricing_plan.question_suggestions %>
</p>
<p>
  <strong>Qrcode share:</strong>
  <%= @pricing_plan.qr_share %>
</p>
<p>
  <strong>Social share:</strong>
  <%= @pricing_plan.social_share %>
</p>
<p>
  <strong>Embed share:</strong>
  <%= @pricing_plan.embed_share %>
</p>
<p>
  <strong>Listen:</strong>
  <%= @pricing_plan.listener %>
</p
<p>
  <strong>Amount:</strong>
  <%= @pricing_plan.amount %>
</p>

<p>
  <strong>Expired Date:</strong>
  <%= @pricing_plan.expired_date %>
</p>

<%= link_to 'Edit', edit_admin_pricing_plan_path(@pricing_plan) %> |
<%= link_to 'Back', admin_pricing_plans_path %>